# Generated by Django 4.2.4 on 2023-09-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=50),
        ),
    ]
